name: mains
on:
  push:
   branches:
     - master
     - main
     - SAST
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: Checkmarx/ast-github-action@2.0.3
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
         branch: ${{ github.ref }}
         additional_params: 
          --threshold "sast-high=1;kics-high=1;sca-high=1;api-high=1"
